name: Go Nancy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Nancy
      uses: sonatype-nexus-community/nancy-github-action@Update_Nancy_To_0.0.33
      with:
        target: go.sum
